### ISSUE TITLE
LWC fails to load after SQLITE attempt

### ISSUE THREAD

**Issue by kauffman214** [pop4959/LWCX#157] opened 2021-05-28 22:52 UTC
**LWC Version (/lwc admin version):** 
[18:43:01 INFO]: [LWC] Enabling LWC v2.2.7-ad0f824

**Server version (/version):** 
paper-1.16.5-662.jar
paper-1.16.5-742.jar

**Short five word summary of issue:** 
LWC will not load after the SQLITE atempt

**Detailed description of problem:**
Running in an iocage on TrueNAS.  Openjdk11.
I've been running this for over a year.  after the last upgrade, I started getting these SQLITE errors.  Which seems to prevent it from loading.  

**If there was an error in console, put it here:**

```
[18:43:01 INFO]: [LWC] Enabling LWC v2.2.7-ad0f824
[18:43:01 INFO]: [LWC] Connecting to SQLite
[18:43:01 WARN]: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
[18:43:01 WARN]: 	at java.base/java.nio.charset.CharsetDecoder.throwIllegalStateException(CharsetDecoder.java:989)
[18:43:01 WARN]: 	at java.base/java.nio.charset.CharsetDecoder.flush(CharsetDecoder.java:672)
[18:43:01 WARN]: 	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:801)
[18:43:01 WARN]: 	at java.base/java.nio.charset.Charset.decode(Charset.java:814)
[18:43:01 WARN]: 	at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507)
[18:43:01 WARN]: 	at org.sqlite.core.NativeDB.column_name(NativeDB.java:239)
[18:43:01 WARN]: 	at org.sqlite.core.DB.column_names(DB.java:733)
[18:43:01 WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131)
[18:43:01 WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
[18:43:01 WARN]: 	at com.griefcraft.sql.PhysDB.doUpdate400_5(PhysDB.java:2177)
[18:43:01 WARN]: 	at com.griefcraft.sql.PhysDB.load(PhysDB.java:423)
[18:43:01 WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1704)
[18:43:01 WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:401)
[18:43:01 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:43:01 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[18:43:01 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[18:43:01 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[18:43:01 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[18:43:01 WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:253)
[18:43:01 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066)
[18:43:01 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[18:43:01 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[18:43:01 ERROR]: Error occurred while enabling LWC v2.2.7-ad0f824 (Is it up to date?)
java.lang.RuntimeException: Failed to prepare statement SELECT id, owner, type, x, y, z, data, blockId, world, password, date, last_accessed FROM lwc_protections ORDER BY id DESC LIMIT ?
	at com.griefcraft.sql.Database.prepare(Database.java:355) ~[?:?]
	at com.griefcraft.sql.Database.prepare(Database.java:332) ~[?:?]
	at com.griefcraft.sql.PhysDB.precache(PhysDB.java:906) ~[?:?]
	at com.griefcraft.lwc.LWC.load(LWC.java:1713) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:401) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-662]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-662]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-662]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-662]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-662]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:253) ~[patched_1.16.5.jar:git-Paper-662]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-662]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-662]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[patched_1.16.5.jar:git-Paper-662]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.16.5.jar:git-Paper-662]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[patched_1.16.5.jar:git-Paper-662]
	at com.griefcraft.sql.Database.prepare(Database.java:350) ~[?:?]
	... 13 more
Caused by: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
	at java.nio.charset.CharsetDecoder.throwIllegalStateException(CharsetDecoder.java:989) ~[?:?]
	at java.nio.charset.CharsetDecoder.flush(CharsetDecoder.java:672) ~[?:?]
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:801) ~[?:?]
	at java.nio.charset.Charset.decode(Charset.java:814) ~[?:?]
	at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507) ~[patched_1.16.5.jar:git-Paper-662]
	at org.sqlite.core.NativeDB.column_name(NativeDB.java:239) ~[patched_1.16.5.jar:git-Paper-662]
	at org.sqlite.core.DB.column_names(DB.java:733) ~[patched_1.16.5.jar:git-Paper-662]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46) ~[patched_1.16.5.jar:git-Paper-662]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[patched_1.16.5.jar:git-Paper-662]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25) ~[patched_1.16.5.jar:git-Paper-662]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[patched_1.16.5.jar:git-Paper-662]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[patched_1.16.5.jar:git-Paper-662]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[patched_1.16.5.jar:git-Paper-662]
	at com.griefcraft.sql.Database.prepareInternal(Database.java:365) ~[?:?]
	at com.griefcraft.sql.Database.lambda$prepare$0(Database.java:350) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065) ~[patched_1.16.5.jar:git-Paper-662]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[patched_1.16.5.jar:git-Paper-662]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.16.5.jar:git-Paper-662]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.16.5.jar:git-Paper-662]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.16.5.jar:git-Paper-662]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.16.5.jar:git-Paper-662]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[patched_1.16.5.jar:git-Paper-662]
	at com.griefcraft.sql.Database.prepare(Database.java:350) ~[?:?]
	... 13 more
[18:43:01 INFO]: [LWC] Disabling LWC v2.2.7-ad0f824

```

**Comment by pop4959** [comment] 2021-05-29 00:59
Strange, there have been no other reports of this (and it's been a while since the update was released). There were also no changes to SQLite support in 2.2.7, as it was fixing an issue that existed only with MySQL.

My guess is most likely that the DB file corrupted in some other way while updating. I'd suggest trying to load one from a backup and see if that works correctly.

**Comment by kauffman214** [comment] 2021-05-29 14:44
I will do that.  Is there any dependency I need to be aware of for SQLite since I'm running it in an iocage jail?
I came across this article on thread safety too which is similar and references the Charset operation
https://stackoverflow.com/questions/6357370/concurrent-database-access-giving-illegalstateexception

**Comment by kauffman214** [comment] 2021-05-29 15:17
I have tried reloading from backup.  I've even tried backing up the lwc.db and LWC directories (separately) and let the system recreate the file.  I get an error on creation and then I get the same error when restarting the server with the new db.

**Comment by pop4959** [comment] 2021-05-29 22:36
The dependency for SQLite is provided by the server, so Paper in your case. The article you linked is not going to be relevant here since LWC's database does not support concurrency (it never has). The only similarity here is the error is related to CharsetDecoder throwing an IllegalStateException.

I've done some testing on my side with LWC 2.2.7-ad0f824 and Paper-745 and fail to reproduce the same error. Everything starts up just fine, as it should. Can you provide more details as to your specific situation? For example, what version(s) of Paper and LWC did you upgrade from. If you run the same upgrade on a different machine and setup, do you still receive the same error?

**Comment by kauffman214** [comment] 2021-05-31 13:50
I've used multiple versions of the plugin and paper.   I will try disabling all plugins and switch to Spigot to see if I get the same issue.

**Comment by kauffman214** [comment] 2021-05-31 22:56
I've been able to recreate this issue on a brand new iocage (truenas jail) on both paper and spigot servers, with LWC as the ONLY plugin.

**Comment by pop4959** [comment] 2021-05-31 23:04
I don't have a way of testing this iocage/truenas setup currently. Are you able to reproduce this error with the exact same server on a setup _different_ from the one that you're running now? If yes, then there might be more to it than the setup itself. I'd be interested to see your files if that's the case in order to check it out on my end. If no, then most likely it is an issue with your setup. Sorry for not clarifying enough last time.

**Comment by kauffman214** [comment] 2021-05-31 23:16
I am not able to create the issue on Ubuntu LTS 20 on bare metal.   My iocage is running inside TrueNAS which is BSD based, not Linux.

**Comment by kauffman214** [comment] 2021-06-01 18:11
I could not wait to resolve the issue, so I backed up everything.  Blew away TrueNas, and put everything on baremetal debian.  It's all working for me.

**Comment by pop4959** [comment] 2021-06-01 18:27
Glad to hear you've resolved the issue for yourself. A wild guess is that were is a bug in the particular version of Java you were using on the BSD system. Not sure if we'd be able to fix it on our end anyways.

Wish you the best going forward. I will close this issue now, but feel free to open a new one if you have any other problems.

**Closed as completed by pop4959** 2021-06-01 18:27 UTC
Labels: problem
