### ISSUE TITLE
Explosion Protection Doesn't Work

### ISSUE THREAD

**Issue by DarkArc** [pop4959/LWCX#169] opened 2021-08-14 20:40 UTC
**LWC Version (/lwc admin version):** Main plugin: 2.2.7-ad0f824
**Server version (/version):** This server is running Paper version git-Paper-186 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 72ce684)

**Short five word summary of issue:** 
Plugin created explosions are not blocked

**Detailed description of problem:**
Explosions created by plugins can still break protected chests, while explosions caused via say, TNT result in the TNT block disappearing.

**Comment by pop4959** [comment] 2021-08-15 01:34
Can you provide more details? If this is caused by a plugin, what plugin is bypassing the protections, and how are you triggering it?

**Comment by DarkArc** [comment] 2021-08-15 02:03
My own, just something as simple as `createExplosion` on the `Location` class.

e.g.
https://github.com/packet-loss-gaming/Grindstone/blob/master/src/main/java/gg/packetloss/grindstone/util/explosion/ExplosionStateFactory.java#L20

**Comment by pop4959** [comment] 2023-02-27 02:06
It doesn't seem like there is much interest in this issue, so I will be closing. I am focusing my time on [Bolt](https://github.com/pop4959/Bolt/wiki) now mostly so if you still see this bug there let me know. It should be much easier to fix as that plugin is effectively a clean version of LWC. Thanks!

**Closed as completed by pop4959** 2023-02-27 02:06 UTC
Labels: wontfix, problem
