### ISSUE TITLE
The Plugin Lacks 1.20 Support

### ISSUE THREAD

**Issue by techgo** [pop4959/LWCX#215] opened 2023-06-09 22:24 UTC
**LWC Version (/lwc admin version):** 2.2.8
**Server version (/version):** 1.20 Paper Build 3

**Short five word summary of issue:** 
The plugin does not load with paper 1.20.

**If there was an error in console, put it here:**
```
[18:12:20] [Server thread/ERROR]: Error occurred while enabling LWC v2.2.8-f367129 (Is it up to date?)
java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at com.griefcraft.util.config.Configuration.<init>(Configuration.java:69) ~[LWCX-2.2.8.jar:?]
	at com.griefcraft.util.config.Configuration.load(Configuration.java:136) ~[LWCX-2.2.8.jar:?]
	at com.griefcraft.util.config.Configuration.load(Configuration.java:105) ~[LWCX-2.2.8.jar:?]
	at com.griefcraft.lwc.LWC.<init>(LWC.java:185) ~[LWCX-2.2.8.jar:?]
	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:346) ~[LWCX-2.2.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.jar:git-Paper-3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.jar:git-Paper-3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.20.jar:git-Paper-3]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.20.jar:git-Paper-3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git-Paper-3]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:12:20] [Server thread/INFO]: [LWC] Disabling LWC v2.2.8-f367129
```

**Comment by pop4959** [comment] 2023-06-09 23:35
Duplicate of #213. This is already fixed in dev builds available on the plugin page. Release will be made soon.

**Closed as completed by pop4959** 2023-06-09 23:35 UTC
Labels: duplicate
