### ISSUE TITLE
Request: Adding support for other faction plugin

### ISSUE THREAD

**Issue by JesFot** [pop4959/LWCX#106] opened 2020-06-04 18:30 UTC
As for now, as far as I know, there is only a support with FactionsUUID.
But in the case another Faction plugin is used (in my case, Factions3) an error is thrown.

Is there a possibility to either ass support for (some) other faction plugin or prevent initialization of faction support if anything other than FactionsUUID is used ?

(Related to #66 )

I will work on a pull-request.

**Comment by pop4959** [comment] 2020-06-04 21:16
Hi, what version of LWC are you using, and what error is thrown? There should not be any errors if an incompatible version of Factions is found, as the integration should not initialize, and simply fail to load and print a warning. Pull request is welcome if it fixes a problem with loading LWC.

Currently FactionsUUID is the only supported Factions plugin, as it is the de facto standand. Development of that plugin is active, and there are about 2-3 developers whom are interested in maintaining its integration with LWC. It should work fine with any plugin (which are most) that are  based from FactionsUUID. It seems like Factions3 is directly based from MassiveCraft, which is why it probably doesn't work. As mentioned in the linked issue, FactionsUUID is also a freemium open source plugin, so there should be no issues with using it (most concerns seem to arise from the fact that they offer paid support).

I am also not personally fond of adding explicit support for multiple Factions clones, as this becomes much more work to maintain in the future. Although, I'm open to chatting with the author of Factions3 if they would like to add their own integration with LWC in their plugin.

**Comment by JesFot** [comment] 2020-06-04 23:15
_**EDIT DOWN THERE ;)**_

Hi, I was mistaken on some points:
Actually, the original MassiveCraft Factions plugin supports LWC by itself by registering its own module (as does Factions3) so there is no need to explicitly support Factions or Factions3.
I thought that the warning was actually preventing some parts of LWC from initialization (that is, breaking the plugin) but no. It is safe.

I DO have the warning at startup:
```
[01:04:24 INFO]: [LWC] Enabling LWC v2.2.5-67bdb89
[01:04:24 INFO]: [LWC] Failed to hook into Factions!
[01:04:24 INFO]: [LWC] Please make sure you are using an updated version of FactionsUUID.
[01:04:24 INFO]: [LWC] https://www.spigotmc.org/resources/factionsuuid.1035/
[01:04:24 WARN]: java.lang.NoClassDefFoundError: com/massivecraft/factions/FPlayer
[01:04:24 WARN]:        at java.lang.Class.getDeclaredMethods0(Native Method)
[01:04:24 WARN]:        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[01:04:24 WARN]:        at java.lang.Class.getDeclaredMethods(Class.java:1975)
[01:04:24 WARN]:        at com.griefcraft.scripting.ModuleLoader.doesObjectOverrideMethod(ModuleLoader.java:332)
[01:04:24 WARN]:        at com.griefcraft.scripting.ModuleLoader.registerFastCache(ModuleLoader.java:242)
[01:04:24 WARN]:        at com.griefcraft.scripting.ModuleLoader.registerModule(ModuleLoader.java:501)
[01:04:24 WARN]:        at com.griefcraft.lwc.LWC.registerModule(LWC.java:1841)
[01:04:24 WARN]:        at com.griefcraft.lwc.LWC.registerCoreModules(LWC.java:1825)
[01:04:24 WARN]:        at com.griefcraft.lwc.LWC.load(LWC.java:1693)
[01:04:24 WARN]:        at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:401)
[01:04:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[01:04:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[01:04:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[01:04:24 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
[01:04:24 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
[01:04:24 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235)
[01:04:24 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900)
[01:04:24 WARN]:        at java.lang.Thread.run(Thread.java:748)
[01:04:24 WARN]: Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.FPlayer
[01:04:24 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[01:04:24 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
[01:04:24 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[01:04:24 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[01:04:24 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[01:04:24 WARN]:        ... 18 more
```
But it is followed by :

```
[01:04:28 INFO]: [Factions 3.3.0] Integration Activated IntegrationLwc
```
some time later, so no issues here.

But during shutdown, here is what I have :

```
[01:04:33 INFO]: [Factions 3.3.0] Integration Deactivation IntegrationLwc FAILED:
[01:04:33 WARN]: java.lang.NullPointerException
[01:04:33 WARN]:        at com.massivecraft.factions.integration.lwc.EngineLwc.setActiveInner(EngineLwc.java:47)
[01:04:33 WARN]:        at com.massivecraft.massivecore.Engine.setActive(Engine.java:80)
[01:04:33 WARN]:        at com.massivecraft.massivecore.Integration.setIntegrationActiveEngines(Integration.java:96)
[01:04:33 WARN]:        at com.massivecraft.massivecore.Integration.setIntegrationActive(Integration.java:67)
[01:04:33 WARN]:        at com.massivecraft.massivecore.Integration.onPluginDisable(Integration.java:170)
[01:04:33 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor74.execute(Unknown Source)
[01:04:33 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[01:04:33 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[01:04:33 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:04:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[01:04:33 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:409)
[01:04:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[01:04:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502)
[01:04:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495)
[01:04:33 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:406)
[01:04:33 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:741)
[01:04:33 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752)
[01:04:33 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:1008)
[01:04:33 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

The line 47 in EngineLWC.java being
```java
LWC.getInstance().getModuleLoader().removeModules(Factions.get());
```

I'm still trying to figure out why the NPE is thrown (maybe the ModuleLoader is no more available ?)
It may also be an issue from MassiveCraft devs, still working on it.

**EDIT :**
Update: it seems that it is an issue with the loading/unloading order... LWC is a ``softdepend`` of (including FactionsUUID) Factions plugin, and as Factions is also a ``softdepend`` of LWC it causes a cyclic soft dependency and, as such, the load order is not certain...
Fix: either remove Factions from LWC ``softdepend``s completly or put it in the ``loadbefore`` (in order to ensure that the Factions plugin is loaded after LWC and unloaded before !
In LWC, the check for the presence of the faction plugin is in the ``onEnable()``, so the Factions plugin is necessarily loaded (``onLoad()``) before (if present). There is no requirements for the Factions plugin to be loaded before LWC.

**Comment by pop4959** [comment] 2020-06-05 01:46
> Actually, the original MassiveCraft Factions plugin supports LWC by itself by registering its own module (as does Factions3) so there is no need to explicitly support Factions or Factions3.

Yep. And this is the recommended way for plugins to integrate with LWC. Their integration could be outdated though. You'd have to ask them to fix it, or get it done yourself.

> I thought that the warning was actually preventing some parts of LWC from initialization (that is, breaking the plugin) but no. It is safe.

This is why I wasn't sure what you meant when you made this issue. If you take a look at the code (1b2beffbd21e1a42812ea0aa800747061d8c2701) you can see that this is a handled exception, however the stack trace is still printed. Maybe this is a bit confusing and could be removed though.

> I'm still trying to figure out why the NPE is thrown (maybe the ModuleLoader is no more available ?)

Nope, the module loader is still used in abundance. If we removed it, almost all integrations with plugins hooking into LWC would break. Whether for better, or for worse, it still exists and remains largely unchanged.

> Update: it seems that it is an issue with the loading/unloading order... LWC is a softdepend of (including FactionsUUID) Factions plugin, and as Factions is also a softdepend of LWC it causes a cyclic soft dependency and, as such, the load order is not certain...

Related issue: #80. As of recent, Spigot forces plugins to add softdepends for any code accessed in other plugins, or it will print a nasty warning. I do not personally agree with their decision, as many plugins do access each other quite frequently, and that shouldn't necessarily be a bug. Softdepend was added in 34ef948f49d25ce4c3bcca9632d4b8b5197434df to address this problem.

> Fix: either remove Factions from LWC softdepends completly or put it in the loadbefore (in order to ensure that the Factions plugin is loaded after LWC and unloaded before !
In LWC, the check for the presence of the faction plugin is in the onEnable(), so the Factions plugin is necessarily loaded (onLoad()) before (if present). There is no requirements for the Factions plugin to be loaded before LWC.

If the load order isn't deterministic, another alternative fix would be to listen to [PluginEnableEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/server/PluginEnableEvent.html) to check for when Factions is loaded.

**Comment by JesFot** [comment] 2020-06-05 08:25
> Nope, the module loader is still used in abundance. If we removed it, almost all integrations with plugins hooking into LWC would break. Whether for better, or for worse, it still exists and remains largely unchanged.

Yes, the NPE is probably from the ``LWC.getInstance()`` as ``LWC#destruct`` sets it to null upon disabling. (And the issue is likely to be LWC disabling BEFORE Factions)

> Related issue: #80 . As of recent, Spigot forces plugins to add softdepends for any code accessed in other plugins, or it will print a nasty warning. I do not personally agree with their decision, as many plugins do access each other quite frequently, and that shouldn't necessarily be a bug. Softdepend was added in [34ef948](https://github.com/pop4959/LWCX/commit/34ef948f49d25ce4c3bcca9632d4b8b5197434df) to address this problem.

There is also the way to reflexively edit ``SimplePluginManager#dependencyGraph`` before calling another plugin classes (just joking, seems like a lot of effort (or is it ?) for a simple, one line, warning)
Or eventually, just print an info message that tells the user that this warning is known and is not causing any issue ? In my case, because of the use of PlaceholderAPI, I have this warning a lot at startup... I stopped caring...

> If the load order isn't deterministic, another alternative fix would be to listen to [PluginEnableEvent ](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/server/PluginEnableEvent.html)to check for when Factions is loaded.

The PluginEnableEvent, seems to be a good idea, but it will not prevent the warning if the "target" plugin is not a ``softdepend``. Also, in the case of FactionsUUID, there is no need for LWC to wait before its actual enabling because the use of the event.

Now that I think of it... what if the Factions plugin is disabled at some point ? Will that not cause some issues ? (This is another issue)

Another workaround would be a delayed task in the ``onDisable``, that would let the time to Factions to unregister from LWC without issues ?

**EDIT**
Maybe a deamon thread with a finalize method ? Or keep the static instance ?
I checked but the ModuleLoader being ``shutdown`` should not cause any issues as ``removeModules`` just won't do anything in case it has already been shutdown

**Comment by pop4959** [comment] 2020-06-05 21:18
> Yes, the NPE is probably from the LWC.getInstance() as LWC#destruct sets it to null upon disabling. (And the issue is likely to be LWC disabling BEFORE Factions)

Factions should be handling NPE. It's not an issue in LWC.

> There is also the way to reflexively edit `SimplePluginManager#dependencyGraph` before calling another plugin classes (just joking, seems like a lot of effort (or is it ?) for a simple, one line, warning)

Yeah, no. Let's not do that.

> Or eventually, just print an info message that tells the user that this warning is known and is not causing any issue ? In my case, because of the use of PlaceholderAPI, I have this warning a lot at startup... I stopped caring...

Don't think this should be necessary for this. I imagine PlaceholderAPI has a much messier dependency "tree" though.

> The PluginEnableEvent, seems to be a good idea, but it will not prevent the warning if the "target" plugin is not a `softdepend`. Also, in the case of FactionsUUID, there is no need for LWC to wait before its actual enabling because the use of the event.

It'll still need to be a softdepend. Not sure what you mean about FactionsUUID, but I don't think it needs any special treatment here.

> Now that I think of it... what if the Factions plugin is disabled at some point ? Will that not cause some issues ? (This is another issue)

Maybe. But like many plugins, I don't think LWC really fully supports reloading. Especially not hot loading or swapping.

> Another workaround would be a delayed task in the onDisable, that would let the time to Factions to unregister from LWC without issues ?
EDIT
> Maybe a deamon thread with a finalize method ? Or keep the static instance ?
I checked but the ModuleLoader being shutdown should not cause any issues as removeModules just won't do anything in case it has already been shutdown

I think you're trying to approach the solution the wrong way here. If other factions plugins like Factions3 are not handling shut downs properly, it needs to be fixed there, not in LWC. Should be able to fix in the exact same way, with loading/unloading via PluginEnableEvent/PluginDisableEvent, or some other sane way.

Here's my suggested solution based on what I'm seeing so far:
- Remove the stack trace from the error (avoids extra confusion for server owners, we know what the warning means).
- Refactor loading the Factions integration (such as with the plugin enable/disable event).
- Similarly refactor loading the LWC integration in the corresponding Factions plugin.

**Comment by JesFot** [comment] 2020-06-07 12:33
> Maybe. But like many plugins, I don't think LWC really fully supports reloading. Especially not hot loading or swapping.

I was thinking more of something like a crash, error or something that would cause CraftBukkit to disable the plugin, but it's very unlikely to happen anyway (or it can wait for an issue to be created regarding this)
Actually, managing the Factions (or others) module with enable/disable events should prevent this from happening.

> I think you're trying to approach the solution the wrong way here. If other factions plugins like Factions3 are not handling shut downs properly, it needs to be fixed there, not in LWC. Should be able to fix in the exact same way, with loading/unloading via PluginEnableEvent/PluginDisableEvent, or some other sane way.

The cause of the error is LWC disabling BEFORE any Factions plugin, as FactionsUUID does not try to unregister its LWC module during disabling it does not create errors but would have if it tries to.
The cause of the NPE being that ``LWC.getInstance()`` returns null.
And they don't have to check for it as they added LWC as a softdepend... (LWC should be disabled after Factions in that case)
I am still here because FactionsUUID also use LWC as a softdepend and registers a module.

> Remove the stack trace from the error (avoids extra confusion for server owners, we know what the warning means).

Yeah, that would be a good idea, and maybe putting the message before as ``WARNING`` and not ``INFO``

> Refactor loading the Factions integration (such as with the plugin enable/disable event).

The only benefit would be if Factions is disabled mid-term. Otherwise I don't see how it would grant anything. When LWC's ``onEnable()`` is called, whether or not Factions is a depend, it's ``onLoad()`` has already been called and the LWC Faction module doesn't even need FactionsUUID to be loaded to work properly as long as FactionsUUID's classes are loaded in memory.

> Similarly refactor loading the LWC integration in the corresponding Factions plugin.

Yep, I'll check if something is going on their sides as well (for Factions3 and MassiveCraft now maintained again Factions)

**EDIT**
On the side of MassiveCraft Factions, they simply removed all suport for LWC 5 month ago (see [here](https://gitlab.massivecraft.team/massivecraft/Factions/-/commit/ad338def4daa05257bd8c67c3bbfb5a063bb59f4))

**Comment by pop4959** [comment] 2020-06-08 21:31
> The cause of the error is LWC disabling BEFORE any Factions plugin, as FactionsUUID does not try to unregister its LWC module during disabling it does not create errors but would have if it tries to.
The cause of the NPE being that LWC.getInstance() returns null.
And they don't have to check for it as they added LWC as a softdepend... (LWC should be disabled after Factions in that case)
I am still here because FactionsUUID also use LWC as a softdepend and registers a module.

I entirely acknowledge your point about other Factions plugins having loading issues with newer versions of LWC, due to the softdepend. As I've already pointed out, FactionsUUID is the only fork of Factions that is currently being supporting. This is not because I don't want to support other forks, but because FactionsUUID is the only fork which is currently dedicated to maintaining an up-to-date integration with LWC.

Having a cyclical soft dependency with Factions is not a bug -- this is just the true nature of the relation between them. Obviously, with a side effect being that the plugins are then loaded in an arbitrary order. Both plugins should be able to handle the case where the other plugin loads either before or after. FactionsUUID currently doesn't have an issue with doing this, so neither should any other Factions plugin.

> Yep, I'll check if something is going on their sides as well (for Factions3 and MassiveCraft now maintained again Factions)

Great! Now we wait to see if they're willing to update their integration.

> On the side of MassiveCraft Factions, they simply removed all suport for LWC 5 month ag

Unfortunate, I guess, but that is their decision to make. However, I don't think there are very many people using this version anymore so it is unlikely to affect users of LWC.

**Comment by pop4959** [comment] 2020-11-14 05:46
I'm going to close this for now, since it doesn't seem like there is much interest, and also Factions3 seems to be unmaintained now.

**Closed as completed by pop4959** 2020-11-14 05:46 UTC
Labels: problem
