### ISSUE TITLE
jdbc4 CommunicationsException

### ISSUE THREAD

**Issue by rumickon** [pop4959/LWCX#45] opened 2019-09-22 10:03 UTC
**LWC Version (/lwc admin version):** 
Main plugin: 2.2.1-5272a54/
**Server version (/version):** 
git-Paper-192 (MC: 1.14.4) 

**Short five word summary of issue:** 
SQL exception in console.

**If there was an error in console, put it here:**
```
[2019-09-22 03:24:28] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.2.1
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCBlockListener.onBlockPlaceMonitor(LWCBlockListener.java:511)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:332)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:231)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:500)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[2019-09-22 03:24:28] [Server thread/WARN]: Caused by: com.griefcraft.scripting.ModuleException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 2,929,866 milliseconds ago.  The last packet sent successfully to the server was 2,018,598 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.griefcraft.sql.Database.printException(Database.java:198)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:199)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.griefcraft.modules.limits.LimitsV2$DefaultLimit.getProtectionCount(LimitsV2.java:176)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.griefcraft.modules.limits.LimitsV2.hasReachedLimit(LimitsV2.java:455)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.griefcraft.modules.limits.LimitsV2.onRegisterProtection(LimitsV2.java:298)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:373)
[2019-09-22 03:24:28] [Server thread/WARN]: 	... 23 more
[2019-09-22 03:24:28] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 2,929,866 milliseconds ago.  The last packet sent successfully to the server was 2,018,598 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[2019-09-22 03:24:28] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedConstructorAccessor162.newInstance(Unknown Source)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2518)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
[2019-09-22 03:24:28] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:193)
[2019-09-22 03:24:28] [Server thread/WARN]: 	... 27 more
[2019-09-22 03:24:28] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[2019-09-22 03:24:29] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.2.1
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCBlockListener.onBlockPlaceMonitor(LWCBlockListener.java:511)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:332)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:231)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:500)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[2019-09-22 03:24:29] [Server thread/WARN]: Caused by: com.griefcraft.scripting.ModuleException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 2,930,917 milliseconds ago.  The last packet sent successfully to the server was 2,019,649 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.griefcraft.sql.Database.printException(Database.java:198)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:199)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.griefcraft.modules.limits.LimitsV2$DefaultLimit.getProtectionCount(LimitsV2.java:176)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.griefcraft.modules.limits.LimitsV2.hasReachedLimit(LimitsV2.java:455)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.griefcraft.modules.limits.LimitsV2.onRegisterProtection(LimitsV2.java:298)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:373)
[2019-09-22 03:24:29] [Server thread/WARN]: 	... 23 more
[2019-09-22 03:24:29] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 2,930,917 milliseconds ago.  The last packet sent successfully to the server was 2,019,649 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[2019-09-22 03:24:29] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedConstructorAccessor162.newInstance(Unknown Source)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2518)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
[2019-09-22 03:24:29] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:193)
[2019-09-22 03:24:29] [Server thread/WARN]: 	... 27 more
[2019-09-22 03:24:29] [Server thread/WARN]: Caused by: java.lang.NullPointerException
```

**Comment by pop4959** [comment] 2019-09-22 19:10
This is sometimes caused by faulty database setup, or more frequently, actual loss of connection with the database server. I cannot help much with this error as it is not caused directly by LWC. Most likely, if you have been using LWC and have not received this error before, you can simply restart both LWC and the database server and check that both communicate properly again. If you are receiving this commonly, I'd look into your database settings, the stability of your network, and maybe even trying a different SQL server implementation. If you want to go the easy route, I recommend using the built-in SQLite implementation, which is server-less (will never encounter this error).

**Comment by rumickon** [comment] 2019-09-23 17:19
I receive this error after 8-10 hours of server start. Other plugins works fine.
Why autoreconnect dont work?

**Comment by pop4959** [comment] 2019-09-24 02:01
Auto-reconnect is already configured for MySQL connections, as shown in the below snippet of code from the plugin (just in case you aren't convinced by me just saying that).

https://github.com/pop4959/LWCX/blob/5272a5434778330d76dac28fd0284761af9161b6/src/main/java/com/griefcraft/sql/Database.java#L236

Why doesn't it work? It could be many things. Most likely a fault in the database setup or software you are using, rather than LWC. I cannot comment further on why you are having problems since you have given me no information yet about your server setup (other than using Paper).

I am willing to help you try to identify and fix the issue, but you need to provide much more information in order for me to do that. The error message is not enough for me to fix this, since I do not have your database, and I do not know how you have set up the plugin to communicate with it, or what you (or the database) did in order to cause this issue. Please help me help you. I can only reasonably be able to look into fixing this problem for you if you can tell me more about it, and provide a way for me to replicate it on my own machine.

Lets start with the following information that may help:
- Provide your configuration (core.yml).
- Full server log.
- MySQL server software and version.
- What other database reliant plugins are being used?
- Details concerning how the SQL server is being networked.

Feel free to send it privately over Discord if you do not wish to post it here. If you have any other information, please do provide as necessary.

**Comment by rumickon** [comment] 2019-09-24 06:24
I already increase "wait_timeout" mysql parameter and need some time for testing.

**Comment by rumickon** [comment] 2019-09-25 16:28
So after testing.
1) The issue is the low value of "wait_timeout" MySQL setting. After increasing the setting, everything works well.
2) autoReconnect does not work. Can you test this?
Please let me know if you still need my configurations.

**Comment by pop4959** [comment] 2019-09-25 20:10
OK, since your problem is solved by wait_timeout I will close this issue. It shouldn't be a problem because of the autoReconnect option, but perhaps your database server does not support this.

I will need further details in order to investigate this further, however. If you can provide me your database configuration in core.yml, server setup (OS, MySQL software + version, SQL configuration), and other relevant information I might be able to test this. Also, what other plugins don't have this problem? I'd be curious to know.

You can send me the information privately over the Discord support server (linked on the plugin page) if you do not wish to post it here. Although, there is really no reason I can think of why you would need to keep it a secret.

Thank you for your understanding.

**Closed as completed by pop4959** 2019-09-25 20:10 UTC
Labels: question, not enough info
