### ISSUE TITLE
LWC informed me about this Exception

### ISSUE THREAD

**Issue by Wolf2323** [pop4959/LWCX#119] opened 2020-08-06 20:06 UTC
**LWC Version (/lwc admin version):** 2.2.6-2d10269
**Server version (/version):** git-Tuinity-"5794d12"

**Short five word summary of issue:** Stacktrave in Console

**Detailed description of problem:**
A User was informed about reporting this to an admin. I am an Admin and Developer, this is the stack trace
What should do?

**If there was an error in console, put it here:**
```
[21:56:23] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: java.sql.SQLException: Generated keys not requested. You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate(), Statement.executeLargeUpdate() or Connection.prepareStatement().
[21:56:23] [Server thread/WARN]: 	at com.griefcraft.sql.Database.printException(Database.java:196)
[21:56:23] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.saveHistory(PhysDB.java:1305)
[21:56:23] [Server thread/WARN]: 	at com.griefcraft.model.History.saveNow(History.java:365)
[21:56:23] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.registerProtection(PhysDB.java:1244)
[21:56:23] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCBlockListener.onBlockPlaceMonitor(LWCBlockListener.java:523)
[21:56:23] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source)
[21:56:23] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:56:23] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:56:23] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:56:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[21:56:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:346)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.ItemStack.placeItem(ItemStack.java:237)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:552)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1434)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1162)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1155)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1230)
[21:56:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[21:56:23] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[21:56:23] [Server thread/WARN]: Caused by: java.sql.SQLException: Generated keys not requested. You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate(), Statement.executeLargeUpdate() or Connection.prepareStatement().
[21:56:23] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[21:56:23] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[21:56:23] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[21:56:23] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[21:56:23] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.getGeneratedKeys(StatementImpl.java:1677)
[21:56:23] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.saveHistory(PhysDB.java:1294)
[21:56:23] [Server thread/WARN]: 	... 25 more
```

**Comment by pop4959** [comment] 2020-08-06 21:00
I haven't seen this stack trace before, but it looks like it is caused by/in LWC's history module.

Can you try setting `core.disableHistory: true` in your core.yml, and let me know if that seems to help? This is completely safe to do if you are not using the history module in LWC. You'd only be using it really if you have an economy hook into LWC.

In addition, it would be helpful if you can provide what system and database software/version you are using. This is because MySQL implementations can vary a bit, so I may need this information in order to attempt reproducing the issue.

**Comment by seyfahni** [comment] 2020-08-07 09:52
Hi, I'm the system admin, here is the info about our system:

Linux System: Debian GNU/Linux 10 (buster)
Kernel: 4.19.0-5-amd64
Database: 10.3.22-MariaDB-0+deb10u1

core.yml
```yaml
core:
    locale: de
    flushInterval: 10
    cacheSize: 10000
    precache: -1
    showNotices: true
    showMyNotices: false
    opIsLWCAdmin: true
    disableHistory: false
    factionCheck: false
    groupPrefix: group.
    updateNotifier: true
database:
    adapter: MySQL
    path: plugins/LWC/lwc.db
    host: localhost
    database: PluginRH
    username: 'xxxx'
    password: 'xxxx'
    prefix: lwc_
    ping_interval: 300
```

We'll try disabling the history module.

**Comment by Haarolean** [comment] 2020-10-03 12:41
@pop4959 that's weird. 
I've checked out this revision: 
- Seems like the only way for this to happen as if `history.doesExist` state would change from `true` to `false` between preparing a statement and it's execution (PhysDB.java:1273 and PhysDB.java:1293);
- Which is totally possible! Since we call `doesExist()` explicitly before and after without saving its state;
- And the only way for this to happen, IIAR, is changing history's state in `DatabaseMigrator`;
- Also, `saving` flag in History not thread safe at all.

@seyfahni @Wolf2323 hey, did turning history off help you? Btw:
1. Is there any chance you were running database setup/migration at the time? 
2. Do you know how to reproduce this?

**Comment by pop4959** [comment] 2020-11-14 06:05
Closing this since there hasn't been any further responses. I'm assuming there haven't been any issues after disabling history (this is something that has helped quite a few people). In the latest dev builds, I've just gone ahead and set history disabled by default for new servers so that this doesn't continue to be a problem. History is not being used by 99.9% of servers, and servers that need it can just turn it back on.

@Haarolean I don't think LWC's database is meant to be run on more than one thread, so I don't suppose thread safety was intended when it was designed. If you see any issues though, feel free to make a PR. It's probably not worth the effort for this though since history is a very much unused/deprecated feature.

**Closed as completed by pop4959** 2020-11-14 06:05 UTC
Labels: problem
