### ISSUE TITLE
[BUG]Double chest protection disappears part2

### ISSUE THREAD

**Issue by sk7z-xyz** [pop4959/LWCX#233] opened 2024-05-26 12:49 UTC
**LWC Version (/lwc admin version):** 
https://www.spigotmc.org/resources/lwc-extended.69551/
Main Plugin 2.3.2
**Server version (/version):** 
This server is running Paper version git-Paper-436 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 850b736)
You are 60 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

**Short five word summary of issue:** 
Double chest protection disappears

**Detailed description of problem:**
1. Place a single chest at coordinates `10, 64, 0`
2. Place another chest at coordinates `11, 64, 0` to create a double chest
3. Break the chest at coordinates `10, 64, 0`
4. Run `/cinfo` and the protection is visible
5. Place StoneBlock at coordinates `10, 64, 0`
6.  `/cinfo` and the protection is gone

https://www.youtube.com/watch?v=NEqhnV4M6FM

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment] 2024-05-26 21:01
Duplicate of #233

**Closed as not planned by pop4959** 2024-05-26 21:01 UTC
Labels: duplicate
